IbwJobeetBundle_job:
    resource: "@IbwJobeetBundle/Resources/config/routing/job.yml"
    prefix: /job
 
ibw_jobeet_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: IbwJobeetBundle:Default:index }


#ibw_jobeet_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: IbwJobeetBundle:Default:index }
#    
ibw_jobeet_homepage:
    pattern:  /
    defaults: { _controller: IbwJobeetBundle:Job:index }
#    
#ibwJobeetBundle_category:
#    pattern:  /category/{slug}
#    defaults: { _controller: IbwJobeetBundle:Category:show }

IbwJobeetBundle_category:
    pattern: /category/{slug}/{page}
    defaults: { _controller: IbwJobeetBundle:Category:show, page: 1 }